version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: *
      POSTGRES_PASSWORD: *
      POSTGRES_DB: *
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: *
      PGADMIN_DEFAULT_PASSWORD: *
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
