version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dima
      POSTGRES_PASSWORD: dima
      POSTGRES_DB: panel
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: 44FUg7Z7
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
