"""empty message

Revision ID: b7cb967c4522
Revises: fa5cf53ce1bb
Create Date: 2024-04-30 11:59:56.404046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cb967c4522'
down_revision: Union[str, None] = 'fa5cf53ce1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('child_group_id_fkey', 'child', type_='foreignkey')
    op.create_foreign_key(None, 'child', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('educator_group_id_fkey', 'educator', type_='foreignkey')
    op.create_foreign_key(None, 'educator', 'group', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'educator', type_='foreignkey')
    op.create_foreign_key('educator_group_id_fkey', 'educator', 'group', ['group_id'], ['id'])
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.create_foreign_key('child_group_id_fkey', 'child', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
