"""empty message

Revision ID: fa5cf53ce1bb
Revises: e3b593070704
Create Date: 2024-04-30 11:41:24.700592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5cf53ce1bb'
down_revision: Union[str, None] = 'e3b593070704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=1), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=1), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educator')
    op.drop_table('child')
    op.drop_table('group')
    # ### end Alembic commands ###
